### ISSUE TITLE
Hardpoint gauge issues (solid instead of outline in RTT, certain external weapon models don't show up)

### ISSUE THREAD

**Issue by WoolieWool** [scp-fs2open/fs2open.github.com#1069]
While working on Wings 2, I have noticed two major issues with the hardpoints gauge available in hud_gauges.tbl. The first is that, when displayed using render-to-texture, it appears as a solid shape instead of an outline, as demonstrated in this screenshot:
http://i.imgur.com/TTlbMX1.jpg

The second is that some external models for secondary weapons don't render on the gauge, and no external primary models render at all. To demonstrate both of these, I have compiled a small mini-mod. Drop the contents of this zip into Blue Planet Complete, load up the mission "Kentauroi Race" (so you won't be bothered by enemy ships or mission objectives), take a UEF Uhlan, enable cheats, and cycle through various primary and secondary weapons. Note that the Uhlan only displays secondary weapons on its third bank. You will see the hardpoints gauge rendered on the Uhlan's cockpit, but as a solid silhouette rather than an outline. Depending on what secondary weapon you have in the third bank, it may show up or it may not. The primary weapons will not appear at all despite the -hdg.tbm specifically instructing the gauge to draw primary weapons.

https://www.sendspace.com/file/9ur5gk

**Comment by z64555** [comment]
Hopefully @SamuelCho (aka Swifty) can help out as soon as he's available. Or at the very least give us blokes some pointers on what to look for. :)

**Comment by WoolieWool** [comment]
Please note that that link to the demo mod will be auto-deleted by Sendspace in another 20 days or so. Got any suggestions as to a more permanent place to put it if Swifty won't be around for a while?

**Comment by niffiwan** [comment]
Mediafire? Or [Freespace Files](http://sectorgame.com/fsfiles/)

**Comment by SamuelCho** [comment]
The reason why a solid shape is drawn is due to the fact that the hardpoints gauge requires a stencil buffer to the destination render target to get the outline effect. Some changes to the RTT system needs to be done in order to fully support stencil/depth buffers in render targets.

**Comment by asarium** [comment]
@WoolieWool Could you upload the test mod again? Fixing this bug should be relatively easy since @SamuelCho already found the reason why this is happening.

**Comment by chief1983** [comment]
@WoolieWool you around still?

**Comment by WoolieWool** [comment]
Sorry for disappearing, here's the reuploaded zip: https://www.sendspace.com/file/vsymxq

**Comment by asarium** [comment]
I tried reproducing this but when I try to launch Kentauroi Race with a UEF Uhlan I do not see a HUD or the cockpit model. Is that the complete mod or do I need something else?

Also, the mod causes a bmpman assertion since the energy bar animation does not have enough frames. I fixed that with #1270 by adding a warning and then ignoring the specified file name.

**Comment by BMagnu** [comment]
Not sure for relevancy, but now that I look at it, it's almost certainly the same fix as #7239.
All it likely needs is the `BMP_FLAG_RENDER_TARGET_DEPTH_ATTACHMENT` flag on cockpit RTT textures + registering the stencil buffer attachment for the FBO.

**Comment by WoolieWool** [comment]
> [@WoolieWool](https://github.com/WoolieWool) Is this still a bug that needs resolving? If we don't hear back by 4/16/2026 we will close this ticket as stale, but feel free to reopen any time if that happens and this bug comes up again.

In FSO 24.2.0 this bug is still active, at least the RTT stencils displaying as a solid block. To test the primary weapon banks not drawing I'm going to have to recreate the Blue Planet patch.
