### ISSUE TITLE
$Enable In-Game Options Disables Settings

### ISSUE THREAD

**Issue by MjnMixael** [scp-fs2open/fs2open.github.com#3375]
This flag, available in Game Settings.tbl seems to disable options like lightshafts and bloom. There does not seem to be options to enable these features in the new Options menu (which does require custom assets... of which my mod does contain). Not sure if that's just unfinished or an oversight. If it's just unfinished, then close this issue and I'll disable this flag for now.

**Comment by jg18** [comment]
@MjnMixael I think I may have a fix. Please see your HLP Forums PMs for a link to a test build, which is based on PR #3501.

Are there any other settings affected by this issue, in addition to lightshafts and bloom?

Thanks!

**Comment by jg18** [comment]
This issue should have been fixed by PR #3501; awaiting confirmation.

**Comment by z64555** [comment]
Did we ever get confirmation of this being fixed or not?

**Comment by jg18** [comment]
@z64555 Not that I'm aware of.

**Comment by MjnMixael** [comment]
This is not fixed. At least not out of the box. If additional work is needed to expose the fix in the librocket Options Menu, I don't have the skill to do that.

However, since the librocket UI seems to be currently abandoned, I'm not sure this is really a priority anymore.

**Comment by MjnMixael** [comment]
I have disabled this flag in BtA. Until In-Game Options becomes more widespread (I don't know of any other mod that uses it), this does not need to be High Priority.

**Comment by MjnMixael** [comment]
Based on my current testing on 22.2, this seems to be fixed.
