### ISSUE TITLE
tiny fix for arm64

### ISSUE THREAD

**Issue by ArminiusTux** [scp-fs2open/fs2open.github.com#6551]
Greetings,

thanks to @notimaginative we can now build FS2Open also for Windows on ARM.
However one of his fixes has not been implemented yet into the main branch.

The `libRocket` dependency is still bound to an old commit:

<img width="1013" alt="Image" src="https://github.com/user-attachments/assets/fe9e9331-040d-4d39-a838-1dee7cbb3f81" />

Please point to the [current master](https://github.com/scp-fs2open/libRocket/) which contains [this small but crucial compilation fix](https://github.com/scp-fs2open/libRocket/commit/49081851f543b97e67c65a9cca7863d7d6c1073e) for arm64 systems.

muchas gracias

**Comment by Goober5000** [comment]
Hmm.  I'm not 100% sure what's going on but I have a theory.  Could you go into your `.gitmodules` file and change `github.com/asarium/` to `github.com/scp-fs2open`, in both places?  Then update your submodules and try to compile again.

If that fixes the issue for you, I'll open a PR.

**Comment by notimaginative** [comment]
Yeah that's my fault. From my command history it looks like I made this change after the libRocket fix hit but reverted it for some (non-technical) reason and then ended up forgetting all about it.

@Goober5000 It's an issue with the FSO repo. Someone needs to checkout the newer libRocket commit in the FSO tree and then PR the change so that the submodule will start pointing to right spot.

(I'm not sure if submodules can follow a branch or if they are stuck being fixed at a specific commit, but it might be worth a look)

**Comment by Goober5000** [comment]
Huh.  Well that's interesting.  Checking out master didn't fix it, but doing `git fetch origin` did.  PR incoming...
